# use Ganache's forked mainnet mode as the default network
networks:
  default: polygon-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts v3.0.0
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.0.0
# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.0.0"
networks:
  default: polygon-fork

wallets:
  from_key: ${}
  from_mnemonic: ${MNEMONIC}

dotenv: .env
